name: test-kikit
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: ./.github/actions/setup-kicad
      - name: Install dependencies and KiKit
        run: |
          sudo apt-get install --yes --no-install-recommends \
            zip inkscape make git libmagickwand-dev \
            libgraphicsmagick1-dev libmagickcore-dev \
            openscad
          python -m pip install PcbDraw
          python -m pip install -e .
      - run: kikit --help
